apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: funnel-frontend
  description: Funnel Frontend
  labels:
    goVersion: go1.15.3
    category: music
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: governance
  system: funnel
